version: '3.9'

services:
  backend:
    build:
      context: ./  # Point to the backend directory
    container_name: ai-chatbot-backend
    ports:
      - "8000:8000"  # Expose backend on port 8000
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - ai-chatbot-net

  frontend:
    build:
      context: ../ai-chatbot-frontend  # Point to the frontend directory
    container_name: ai-chatbot-frontend
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}  
    depends_on:
      - backend  # Ensure backend starts first
    networks:
      - ai-chatbot-net

networks:
  ai-chatbot-net:
    driver: bridge  # Bridge network for the frontend and backend to communicate
